/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.kehadiranfrontend;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.net.URL;
import java.net.URLConnection;
import java.net.URLEncoder;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Anzhari
 */
public class KehadiranUI extends javax.swing.JFrame {

    /**
     * Creates new form KehadiranUI
     * @param urlString
     * @return 
     * @throws java.lang.Exception
     */
    public static String readUrl(String urlString) throws Exception {
        BufferedReader reader = null;
        URL url;
        url = new URL(urlString);
        URLConnection connection = url.openConnection();
        StringBuilder response;
        try (BufferedReader in = new BufferedReader(
                new InputStreamReader(
                        connection.getInputStream()))) {
            response = new StringBuilder();
            String inputLine;
            while ((inputLine = in.readLine()) != null)
                response.append(inputLine);
        }        
        return response.toString();
    }
    
    /**
     *
     * @param urlString
     * @param idakun
     * @param tgl_lahir
     * @param tahun
     * @param bulan
     * @param usr_pass
     * @return
     * @throws Exception
     */
    public static JsonObject getKehadiran(String urlString, String idakun, 
            String tgl_lahir, String tahun, String bulan, String usr_pass) 
            throws Exception {
        BufferedReader reader = null;
        String urlParamString;
        urlParamString = urlString;
        urlParamString += "?";
        urlParamString += "idakun=";
        urlParamString += URLEncoder.encode(idakun, "UTF-8");
        urlParamString += "&";
        urlParamString += "tgl_lahir=";
        urlParamString += URLEncoder.encode(tgl_lahir, "UTF-8");
        urlParamString += "&";
        urlParamString += "tahun=";
        urlParamString += URLEncoder.encode(tahun, "UTF-8");
        urlParamString += "&";
        urlParamString += "bulan=";
        urlParamString += URLEncoder.encode(bulan, "UTF-8");
        urlParamString += "&";
        urlParamString += "usr_pass=";
        urlParamString += URLEncoder.encode(usr_pass, "UTF-8");
        URL url;
        url = new URL(urlParamString);
        URLConnection connection = url.openConnection();
        StringBuilder response;
        try (BufferedReader in = new BufferedReader(
                new InputStreamReader(
                        connection.getInputStream()))) {
            response = new StringBuilder();
            String inputLine;
            while ((inputLine = in.readLine()) != null)
                response.append(inputLine);
        }        
        System.out.println(response.toString());
        GsonBuilder builder = new GsonBuilder();
        Gson gson = builder.create();
        JsonObject jsonObject;
        jsonObject = gson.fromJson(response.toString(), JsonObject.class);
        return jsonObject;
    }
    public KehadiranUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        formview = new javax.swing.JPanel();
        id_karyawan_label = new javax.swing.JLabel();
        tgl_lahir_label = new javax.swing.JLabel();
        tahun_label = new javax.swing.JLabel();
        bulan_label = new javax.swing.JLabel();
        id_karyawan = new javax.swing.JTextField();
        tgl_lahir = new javax.swing.JTextField();
        tahun = new javax.swing.JTextField();
        bulan = new javax.swing.JTextField();
        submit = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        bulan_label1 = new javax.swing.JLabel();
        usr_password = new javax.swing.JPasswordField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabel_output = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Klien Desktop Java API Kehadiran");

        formview.setBorder(javax.swing.BorderFactory.createTitledBorder("Form"));

        id_karyawan_label.setText("ID Karyawan");

        tgl_lahir_label.setText("Tanggal Lahir");

        tahun_label.setText("Tahun");

        bulan_label.setText("Bulan");

        id_karyawan.setText("ID Karyawan");

        tgl_lahir.setText("YYYYMMDD");

        tahun.setText("YYYY");

        bulan.setText("MM");

        submit.setText("Submit");
        submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitMouseClicked(evt);
            }
        });

        clear.setText("Clear");
        clear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearMouseClicked(evt);
            }
        });

        bulan_label1.setText("Password");

        usr_password.setText("jPasswordField1");

        javax.swing.GroupLayout formviewLayout = new javax.swing.GroupLayout(formview);
        formview.setLayout(formviewLayout);
        formviewLayout.setHorizontalGroup(
            formviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formviewLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formviewLayout.createSequentialGroup()
                        .addGroup(formviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(id_karyawan_label)
                            .addComponent(tgl_lahir_label)
                            .addComponent(tahun_label)
                            .addComponent(bulan_label)
                            .addComponent(bulan_label1))
                        .addGap(26, 26, 26)
                        .addGroup(formviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(id_karyawan, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                            .addComponent(tgl_lahir)
                            .addComponent(tahun)
                            .addComponent(bulan)
                            .addComponent(usr_password)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formviewLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(submit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clear)))
                .addContainerGap())
        );
        formviewLayout.setVerticalGroup(
            formviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formviewLayout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(formviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(id_karyawan_label)
                    .addComponent(id_karyawan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tgl_lahir_label)
                    .addComponent(tgl_lahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tahun_label)
                    .addComponent(tahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bulan_label)
                    .addComponent(bulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bulan_label1)
                    .addComponent(usr_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(formviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submit)
                    .addComponent(clear)))
        );

        tabel_output.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tanggal", "Nama", "Divisi", "Masuk", "Pulang"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabel_output);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(formview, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(formview, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitMouseClicked
        // TODO add your handling code here:
        DefaultTableModel tabel_model;
        tabel_model = (DefaultTableModel) tabel_output.getModel();
        tabel_model.setRowCount(0);
        String urlString = "http://localhost:18080/kehadiran";
        JsonObject readUrl;
        String param_id_akun;
        String param_tgl_lahir;
        String param_tahun;
        String param_bulan;
        String param_usr_password;
        JsonElement kehadiranStatus;
        JsonElement kehadiranMessage;
        JsonElement kehadiranData;
        param_id_akun = id_karyawan.getText();
        param_tgl_lahir = tgl_lahir.getText();
        param_tahun = tahun.getText();
        param_bulan = bulan.getText();
        param_usr_password = new String(usr_password.getPassword());
        try {        
            readUrl = getKehadiran(urlString, param_id_akun, param_tgl_lahir, param_tahun, param_bulan, param_usr_password);
            kehadiranStatus = readUrl.get("status");
            kehadiranMessage = readUrl.get("message");
            kehadiranData = readUrl.get("data");
            Boolean kehadiranDataisJsonObject = kehadiranData.isJsonObject();
            Boolean kehadiranDataisJsonArray = kehadiranData.isJsonArray();
            Boolean kehadiranDataisJsonPrimitive = kehadiranData.isJsonPrimitive();
            System.out.println("kehadiranDataisJsonObject: " + kehadiranDataisJsonObject);
            System.out.println("kehadiranDataisJsonArray: " + kehadiranDataisJsonArray);
            System.out.println("kehadiranDataisJsonPrimitive: " + kehadiranDataisJsonPrimitive);
            if (kehadiranDataisJsonPrimitive) {
                JOptionPane.showMessageDialog(null, "Status: " + kehadiranStatus.getAsString() + "\nPesan: " + kehadiranMessage.getAsString());
            } else if (kehadiranDataisJsonArray) {
                int jsonlen = kehadiranData.getAsJsonArray().size();
                for (int x = 0; x < jsonlen; x = x + 1) {
                    String id_record = readUrl.getAsJsonArray("data").get(x).getAsJsonArray().get(0).getAsString();
                    String tanggal = readUrl.getAsJsonArray("data").get(x).getAsJsonArray().get(1).getAsString();  
                    String id_akun = readUrl.getAsJsonArray("data").get(x).getAsJsonArray().get(2).getAsString();              
                    String nama = readUrl.getAsJsonArray("data").get(x).getAsJsonArray().get(3).getAsString();  
                    String id_divisi = readUrl.getAsJsonArray("data").get(x).getAsJsonArray().get(4).getAsString();
                    String nama_div = readUrl.getAsJsonArray("data").get(x).getAsJsonArray().get(5).getAsString();
                    String masuk = readUrl.getAsJsonArray("data").get(x).getAsJsonArray().get(6).getAsString();
                    String pulang = readUrl.getAsJsonArray("data").get(x).getAsJsonArray().get(7).getAsString();
                    tabel_model.addRow(new Object[]{tanggal, nama, nama_div, masuk, pulang});
                }
                JOptionPane.showMessageDialog(null, "Status: " + kehadiranStatus.getAsString() + "\nPesan: " + kehadiranMessage.getAsString());
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Status: error\nPesan: Gagal menghubungi server API. Hubungi Administrator. "); 
            Logger.getLogger(KehadiranUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_submitMouseClicked

    private void clearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearMouseClicked
        // TODO add your handling code here:
        DefaultTableModel tabel_model;
        tabel_model = (DefaultTableModel) tabel_output.getModel();
        tabel_model.setRowCount(0);
        tahun.setText("YYYY");
        bulan.setText("MM");
        JOptionPane.showMessageDialog(null, "Status: OK\nPesan: Input dan data dihapus");
    }//GEN-LAST:event_clearMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KehadiranUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KehadiranUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KehadiranUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KehadiranUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KehadiranUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bulan;
    private javax.swing.JLabel bulan_label;
    private javax.swing.JLabel bulan_label1;
    private javax.swing.JButton clear;
    private javax.swing.JPanel formview;
    private javax.swing.JTextField id_karyawan;
    private javax.swing.JLabel id_karyawan_label;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton submit;
    private javax.swing.JTable tabel_output;
    private javax.swing.JTextField tahun;
    private javax.swing.JLabel tahun_label;
    private javax.swing.JTextField tgl_lahir;
    private javax.swing.JLabel tgl_lahir_label;
    private javax.swing.JPasswordField usr_password;
    // End of variables declaration//GEN-END:variables
}
